from django.db import models
from django.core.validators import RegexValidator
from frontend.models import ExperimentMember

alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')

class OnboardCode(models.Model):
    # These are the codes needed to onboard, autogenerated in file
    # Found in file static/data/onboard_code_database.csv
    # Registered by management command python manage.py register_onboard_code
    onboard_code = models.CharField(max_length=6)
    registered_user = models.OneToOneField(ExperimentMember, on_delete=models.SET_NULL, blank=True, null=True, default=None)

    def __str__(self):
        return f'OnboardCoe: {self.onboard_code}'


class ZipCodeInfo(models.Model):
    # All of these zip codes are guaranteed to be legitimate, downloaded from https://www.unitedstateszipcodes.org/
    # Found in file static/data/zip_code_database.csv
    # Registered by management command python manage.py register_zip_code
    zip = models.CharField(max_length=5)
    zip_type = models.CharField(
        max_length = 8,
        choices = [
            ('UNIQUE', 'UNIQUE'),
            ('STANDARD', 'STANDARD'),
            ('POBOX', 'PO BOX'),
            ('MILITARY', 'MILITARY')
        ]
    )
    is_decommissioned = models.BooleanField()
    primary_city = models.CharField(max_length=50)
    state = models.CharField(max_length=2)
    county = models.CharField(max_length=50)
    latitude = models.DecimalField(max_digits=6, decimal_places=2)
    longitude = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f'ZipCode: {self.zip}'


class ProlificId(models.Model):
    # The 24 character alphanumeric Prolific ID needed to onboard.
    prolific_id = models.CharField(max_length=24, validators=[alphanumeric])
    user_id = models.OneToOneField(ExperimentMember, on_delete=models.CASCADE)

    def __str__(self):
        return f'ProlificId: {self.prolific_id}'


class Demographics(models.Model):
    # NOTE: Can go through this code to note the codes for each of the responses.
    user_id = models.OneToOneField(ExperimentMember, on_delete=models.CASCADE)
    age = models.CharField(
        max_length = 1,
        choices = [
            ('1', '18 to 24'),
            ('2', '25 to 34'),
            ('3', '35 to 50'),
            ('4', '51 to 65'),
            ('5', '65 and above'),
        ],
        default = None,
        blank = False,
    )
    gender = models.CharField(
        max_length = 1,
        choices = [
            ('M', 'Male'),
            ('W', 'Female'),
            ('N', 'Non-binary'),
            ('E', 'Something else'),
            ('P', 'Prefer not to say'),

        ],
        default = None,
        blank = False,
    )
    race = models.CharField(
        max_length = 6,
        # Choices defined within forms.py and selections concatenated
        # Key: (W)hite, (B)lack or African American, (N) American Indian or Alaska Native,
        # (P)acific Islander or Native Hawaiian, (A)sian or Asian American, (O)ther
        default = None,
        blank = False,
    )
    state = models.CharField(
        max_length = 2,
        choices = [
            ('AL', 'Alabama'),  ('AK', 'Alaska'),   ('AZ', 'Arizona'),
            ('AR', 'Arkansas'), ('CA', 'California'),   ('CO', 'Colorado'),
            ('CT', 'Connecticut'),  ('DE', 'Delaware'), ('FL', 'Florida'),
            ('GA', 'Georgia'),  ('HI', 'Hawaii'),   ('ID', 'Idaho'),
            ('IL', 'Illinois'), ('IN', 'Indiana'),  ('IA', 'Iowa'),
            ('KS', 'Kansas'),   ('KY', 'Kentucky'), ('LA', 'Louisiana'),
            ('ME', 'Maine'),    ('MD', 'Maryland'), ('MA', 'Massachusetts'),
            ('MI', 'Michigan'), ('MN', 'Minnesota'),    ('MO', 'Missouri'),
            ('MS', 'Mississippi'), ('MT', 'Montana'),  ('NE', 'Nebraska'), ('NV', 'Nevada'),
            ('NH', 'New Hampshire'),    ('NJ', 'New Jersey'),   ('NM', 'New Mexico'),
            ('NY', 'New York'), ('NC', 'North Carolina'),   ('ND', 'North Dakota'),
            ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'),
            ('OR', 'Oregon'),   ('PW', 'Palau'),    ('PA', 'Pennsylvania'),
            ('RI', 'Rhode Island'), ('PR', 'Puerto Rico'),  ('SC', 'South Carolina'),
            ('SD', 'South Dakota'), ('TN', 'Tennessee'),    ('TX', 'Texas'),
            ('VT', 'Vermont'),  ('VA', 'Virginia'), ('WA', 'Washington'),
            ('DC', 'Washington, D.C.'), ('WV', 'West Virginia'),    ('WI', 'Wisconsin'),
            ('WY', 'Wyoming'),  ('VI', 'Virgin Islands'), ('NA', 'Not in U.S. Territory or State'),
            ('UT', 'Utah'),
            (None, 'Please Select a State'),
        ],
        default = None,
        blank = False,
    )
    zipcode = models.CharField(
        max_length = 5,
        # Further validation done in forms.py, looking for 5 digit answer.
        default = None,
        blank = False,
    )
    education = models.CharField(
        max_length = 1,
        choices = [
            ('<', 'Less than high school'),
            ('H', 'High school graduate'),
            ('C', 'Some college'),
            ('4', '4 year college degree'),
            ('P', 'Advanced degree (doctorate, masters, or other professional degrees)')
        ],
        default = None,
        blank = False,
        verbose_name = 'Education Level',
    )
    household_income = models.CharField(
        max_length = 1,
        choices = [
            ('<', '$30,000 or less'),
            ('2', '$30,000 up to $69,999'),
            ('3', '$70,000 up to $99,999'),
            ('4', '$100,000 up to $200,000'),
            ('>', '$200,000 or more'),
        ],
        default = None,
        blank = False,
        verbose_name = 'Household Income',
    )
    pol_ideology = models.CharField(
        max_length = 2,
        choices = [
            ('SD', 'Strong Democrat'),
            ('WD', 'Weak Democrat'),
            ('LD', 'Leaning Democrat'),
            ('IN', 'Independent'),
            ('LR', 'Leaning Republican'),
            ('WR', 'Weak Republican'),
            ('SR', 'Strong Republican'),
        ],
        default = None,
        blank = False,
        verbose_name = 'Political Ideology',
    )
    pol_scale = models.CharField(
        max_length = 2,
        choices = [
            ('EL', 'Extremely liberal'),
            ('LI', 'Liberal'),
            ('SL', 'Slightly liberal'),
            ('MO', 'Moderate; middle of the road'),
            ('SC', 'Slightly conservative'),
            ('CO', 'Conservative'),
            ('EC', 'Extremely conservative'),
        ],
        default = None,
        blank = False,
        null=True,
        verbose_name = 'Liberal Conservative',
    )
    past_voting = models.CharField(
        max_length = 1,
        choices = [
            ('N', 'None'),
            ('F', 'Few'),
            ('H', 'About half'),
            ('M', 'Most'),
            ('A', 'All'),
            ('D', 'I don\'t remember'),
            ('0', 'Not applicable')
        ],
        default = None,
        blank = False,
        verbose_name = 'Voting in Previous Elections',
    )

    def __str__(self):
        return f'DemographicsForm for {self.user_id}'
