"""
Django base settings for intervenr project.
This is the base file, will be loaded with production.py or local.py. 
See __init__.py for loading order.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path
import os
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# NOTE: Added an extra parent so that the base path resolves to root intervenr, instead of subdirectory intervenr
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
# SECRET KEY REMOVED -- CHECK YOUR local.py SETTINGS, DO NOT PUT IN GIT


# ALLOWED_HOSTS: overridden by local.py (localhost) and production.py (real hosts).
# This base value is never used directly, kept empty since it's always reassigned.
ALLOWED_HOSTS = []


# List of admins to receive details of exceptions raised in request/ response cycle.
# https://docs.djangoproject.com/en/4.2/ref/settings/#admins
# Set ADMIN_NAME / ADMIN_EMAIL env vars to enable; left unset, no admin emails are sent.
ADMINS = (
    [(os.environ.get('ADMIN_NAME', 'Admin'), os.environ['ADMIN_EMAIL'])]
    if os.environ.get('ADMIN_EMAIL') else []
)


# Application Definitions
# 3rd Party Applications: 
# corsheaders - (django-cors-headers: https://github.com/adamchainz/django-cors-headers)
# storages - (django-storages: https://django-storages.readthedocs.io/en/latest/)
#            NOTE: Automatically requires boto3 installation (https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) 
# social_django - (social-auth-app-django: https://python-social-auth.readthedocs.io/en/latest/configuration/django.html)
# crispy_forms - (https://django-crispy-forms.readthedocs.io/)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'storages',
    'social_django',
    'django_user_agents',
    'frontend.apps.FrontendConfig',
    'onboard.apps.OnboardConfig',
    'extension.apps.ExtensionConfig',
    'ads_extension.apps.AdsExtensionConfig',
    'crispy_forms',
    "crispy_bootstrap4",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'intervenr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

WSGI_APPLICATION = 'intervenr.wsgi.application'


# CORS Settings
# See here: https://github.com/adamchainz/django-cors-headers#setup
# Right now, only /extension/* endpoints need CORS exemptions.
CORS_ALLOW_ALL_ORIGINS = True
CORS_URLS_REGEX = r'^/.*extension/.*$'


# Database
# NOTE: Not directly in base.py, see local.py or production.py


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

# NOTE: For simplicity, by default disable timezones. Everything will be in reference to server time.
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# NOTE: Not directly included in base.py, see production.py or local.py


# Python Social Auth (social_django) Settings
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'

SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/onboard/redirect_prolific/'

SOCIAL_AUTH_JSONFIELD_ENABLED = True

SOCIAL_AUTH_URL_NAMESPACE = 'social'

# NOTE: Twitter & FB never set up
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    # 'social_core.backends.twitter.TwitterOAuth',
    # 'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'onboard.pipeline.is_login_attempt_valid',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'onboard.pipeline.link_new_account',
]

SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
]

# Contact email of an internal test account, used to bypass certain study
# gating logic during QA. Set via TEST_ACCOUNT_EMAIL env var; left unset,
# the bypass never matches.
TEST_ACCOUNT_EMAIL = os.environ.get('TEST_ACCOUNT_EMAIL', '')

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

USER_AGENTS_CACHE = None

RUNNING_PROD = not (len(sys.argv) > 1 and sys.argv[1] == 'runserver')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': ('%(asctime)s [%(process)d] [%(levelname)s] ' +
                       'pathname=%(pathname)s lineno=%(lineno)s ' +
                       'funcname=%(funcName)s %(message)s'),
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        }
    },
    'root': {
        'handlers': ['console', 'mail_admins'],
        'level': 'WARNING',
    },
}