# Generated by Django 3.2 on 2021-10-05 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0012_auto_20210927_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(default=datetime.datetime.now)),
                ('participant_alert_all', models.BooleanField(default=False)),
                ('participant_alert_intervention_type', models.CharField(max_length=100)),
                ('participant_message', models.CharField(max_length=17)),
                ('participant_alert_url', models.CharField(max_length=2000)),
                ('participant_alert_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(default=datetime.datetime.now)),
                ('request_json', models.JSONField()),
                ('message', models.CharField(default='NA', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AdRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('src_page_hash', models.TextField()),
                ('ad_hash', models.TextField()),
                ('content_type', models.TextField()),
                ('ad_title', models.TextField()),
                ('target_url', models.TextField()),
                ('src_page_title', models.TextField()),
                ('src_page_url', models.TextField()),
                ('ad_network', models.TextField()),
                ('img_src', models.TextField()),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('text_title', models.TextField()),
                ('text_body_text', models.TextField()),
                ('text_site', models.TextField()),
                ('participant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
