# Generated by Django 3.2 on 2021-10-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrecord',
            name='ad_network',
            field=models.TextField(blank=True, null=True),
        ),
    ]
