# Generated by Django 3.2 on 2021-10-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0002_alter_adrecord_ad_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrecord',
            name='img_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='img_src',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='img_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='text_body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='text_site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='text_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
