# Generated by Django 3.2 on 2021-10-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0003_auto_20211005_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='page_domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='target_domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='target_hostname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
