# Generated by Django 3.2 on 2021-10-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210927_1920'),
        ('ads_extension', '0004_auto_20211009_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_method', models.TextField()),
                ('data_type', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ad_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads_extension.adrecord')),
                ('participant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
    ]
