# Generated by Django 3.2 on 2021-12-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0005_admetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
