# Generated by Django 3.2 on 2022-02-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0006_auto_20211215_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='intervenr_ad_type',
            field=models.IntegerField(choices=[(0, 'Obs'), (1, 'Interv Orig'), (2, 'Interv Swap')], default=0),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='original_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads_extension.adrecord'),
        ),
    ]
