# Generated by Django 3.2 on 2022-02-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0006_auto_20211215_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admetadata',
            name='ad_record',
        ),
    ]
