# Generated by Django 3.2 on 2022-02-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0010_admetadata_ad_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdMetadata',
        ),
    ]
