# Generated by Django 3.2 on 2022-02-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0007_auto_20220207_1810'),
        ('ads_extension', '0012_admetadata'),
    ]

    operations = [
    ]
