# Generated by Django 3.2 on 2022-02-28 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20220219_0508'),
        ('ads_extension', '0013_merge_0007_auto_20220207_1810_0012_admetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRecordRedaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('n_deleted', models.IntegerField(default=0)),
                ('participant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
    ]
