# Generated by Django 3.2 on 2022-02-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0014_adrecordredaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrecord',
            name='intervenr_ad_type',
            field=models.IntegerField(choices=[(0, 'Obs'), (1, 'Interv Orig'), (2, 'Interv Swap'), (3, 'To Ignore')], default=0),
        ),
    ]
