# Generated by Django 3.2 on 2022-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0017_auto_20220301_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField()),
                ('ad_record_id', models.UUIDField()),
                ('extraction_method', models.TextField()),
                ('data_type', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
