# Generated by Django 3.2 on 2022-06-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_extension', '0018_admetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='img_was_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
