# Generated by Django 3.2 on 2022-07-19 22:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_experimentsettings_exp_name'),
        ('ads_extension', '0019_adrecord_img_was_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('participant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
    ]
