# Generated by Django 3.1.7 on 2021-04-13 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentMember',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('extension_registered', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('bazinga', models.EmailField(blank=True, max_length=254)),
                ('social_auth', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
