# Generated by Django 3.1.7 on 2021-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmember',
            name='interventionField',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
