# Generated by Django 3.1.7 on 2021-05-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_experimentmember_interventionfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmember',
            name='interventionField',
            field=models.IntegerField(default=0),
        ),
    ]
