# Generated by Django 3.1.7 on 2021-07-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210507_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentmember',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='experimentmember',
            name='bazinga',
        ),
        migrations.RemoveField(
            model_name='experimentmember',
            name='interventionField',
        ),
        migrations.AddField(
            model_name='experimentmember',
            name='intervention_type',
            field=models.TextField(default='control', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentmember',
            name='offboard_user',
            field=models.BooleanField(default=False),
        ),
    ]
