# Generated by Django 3.1.7 on 2021-07-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210724_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmember',
            name='intervention_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
