# Generated by Django 3.1.7 on 2021-07-29 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20210724_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmember',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
