# Generated by Django 3.1.7 on 2021-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210729_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmember',
            name='offboard_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
