# Generated by Django 3.1.7 on 2021-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_experimentmember_offboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmember',
            name='intervention_type',
            field=models.CharField(blank=True, default='control', max_length=100, null=True),
        ),
    ]
