# Generated by Django 3.1.7 on 2021-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210810_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmember',
            name='middle_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experimentmember',
            name='offboard_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experimentmember',
            name='onboard_survey',
            field=models.BooleanField(default=False),
        ),
    ]
