# Generated by Django 3.1.7 on 2021-08-20 15:55

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210818_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmember',
            name='intervention_type',
            field=models.CharField(blank=True, default=frontend.models.rand_experimental_group, max_length=100, null=True),
        ),
    ]
