# Generated by Django 3.1.7 on 2021-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210818_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmember',
            name='first_q',
            field=models.TextField(default='Not answered', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentmember',
            name='second_q',
            field=models.TextField(default='Not answered', max_length=2000),
            preserve_default=False,
        ),
    ]
