# Generated by Django 3.2.7 on 2021-09-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210820_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmember',
            name='experiment_type',
            field=models.IntegerField(choices=[(0, 'Not Assigned'), (1, 'News'), (2, 'Ads')], default=0),
        ),
        migrations.AddField(
            model_name='experimentmember',
            name='has_onboard_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experimentmember',
            name='has_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
