# Generated by Django 3.1.7 on 2021-08-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210820_1555'),
        ('frontend', '0011_auto_20210824_1146'),
    ]

    operations = [
    ]
