# Generated by Django 3.1.7 on 2021-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_merge_20210824_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmember',
            name='onboard_survey',
            field=models.BooleanField(default=True),
        ),
    ]
