# Generated by Django 3.2 on 2021-11-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210927_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_json', models.JSONField(null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
    ]
