# Generated by Django 3.2 on 2021-10-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210927_1920'),
        ('frontend', '0013_auto_20210824_1201'),
    ]

    operations = [
    ]
