# Generated by Django 3.2 on 2021-11-16 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_finalsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsurvey',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='introsurvey',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
