# Generated by Django 3.2 on 2021-11-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_merge_0012_auto_20210927_1920_0013_auto_20210824_1201'),
        ('frontend', '0015_auto_20211116_0308'),
    ]

    operations = [
    ]
