# Generated by Django 3.2 on 2022-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_midpointsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmember',
            name='onboard_survey',
            field=models.BooleanField(default=False),
        ),
    ]
