# Generated by Django 3.2 on 2022-02-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_alter_experimentmember_onboard_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmember',
            name='swap_partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.experimentmember'),
        ),
        migrations.AlterField(
            model_name='experimentmember',
            name='first_q',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='experimentmember',
            name='second_q',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
