# Generated by Django 3.2 on 2022-02-28 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20220219_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('obs_start', models.DateField(default=datetime.date.today)),
                ('obs_end', models.DateField(default=None)),
                ('interv_start', models.DateField(default=None)),
                ('interv_end', models.DateField(default=None)),
            ],
        ),
    ]
