# Generated by Django 3.2 on 2022-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_experimentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsettings',
            name='exp_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
