# Generated by Django 4.2.2 on 2023-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0021_experimentsettings_exp_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmember",
            name="onboard_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
