# Generated by Django 4.2.2 on 2023-11-01 22:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0023_alter_experimentmember_social_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmember",
            name="second_middle_survey",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SecondMidpointSurvey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(default=datetime.datetime.now)),
                ("response_json", models.JSONField(null=True)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.experimentmember",
                    ),
                ),
            ],
        ),
    ]
