# Generated by Django 3.1.7 on 2021-04-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('1', '18 to 24'), ('2', '25 to 34'), ('3', '35 to 44'), ('4', '45 to 54'), ('5', '55 to 64'), ('6', '65 and above')], default=None, max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'Non-binary'), ('E', 'Something else'), ('P', 'Prefer not to say')], default=None, max_length=1)),
                ('race', models.CharField(default=None, max_length=20)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PW', 'Palau'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('PR', 'Puerto Rico'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('DC', 'Washington, D.C.'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('VI', 'Virgin Islands'), ('NA', 'Not in U.S. Territory or State'), (None, 'Please Select a State')], default=None, max_length=2)),
                ('zipcode', models.CharField(default=None, max_length=5)),
                ('education', models.CharField(choices=[('<', 'Less than high school'), ('H', 'High school graduate'), ('C', 'Some college'), ('2', '2 year degree'), ('4', '4 year degree'), ('P', 'Doctorate, masters, or other professional degrees')], default=None, max_length=1, verbose_name='Education Level')),
                ('household_income', models.CharField(choices=[('<', '$15,000 or less'), ('2', '$15,000 up to $25,999'), ('3', '$26,000 up to $36,999'), ('4', '$37,000 up to $49,999'), ('5', '$50,000 up to $62,999'), ('6', '$63,000 up to $78,999'), ('7', '$79,000 up to $99,999'), ('8', '$100,000 up to $129,999'), ('9', '$130,000 up to $183,999'), ('>', '$184,000 or more')], default=None, max_length=1, verbose_name='Household Income')),
                ('pol_ideology', models.CharField(choices=[('VL', 'Very liberal'), ('LI', 'Liberal'), ('SL', 'Slightly liberal'), ('MO', 'Moderate'), ('SC', 'Slightly conservative'), ('CO', 'Conservative'), ('VC', 'Very conservative'), ('NA', 'None of these describe my political leanings')], default=None, max_length=2, verbose_name='Political Ideology')),
                ('pol_party', models.CharField(choices=[('S', "Don't know / not sure"), ('N', 'Not registered with any political party'), ('D', 'Democratic Party'), ('R', 'Republican Party'), ('I', 'Independent'), ('O', 'Other')], default=None, max_length=1, verbose_name='Political Party')),
                ('past_voting', models.CharField(choices=[('N', 'None'), ('F', 'Few'), ('H', 'About half'), ('M', 'Most'), ('A', 'All'), ('D', "I don't remember")], default=None, max_length=1, verbose_name='Voting in Previous Elections')),
                ('pol_engagement', models.CharField(choices=[('E', 'Extremely engaged'), ('V', 'Very engaged'), ('M', 'Moderately engaged'), ('S', 'Slightly engaged'), ('N', 'Not at all engaged')], default=None, max_length=1, verbose_name='Political Engagement')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
    ]
