# Generated by Django 3.1.7 on 2021-05-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='race',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
