# Generated by Django 3.1.7 on 2021-07-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210716_1646'),
        ('onboard', '0002_auto_20210514_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=5)),
                ('zip_type', models.CharField(choices=[('UNIQUE', 'UNIQUE'), ('STANDARD', 'STANDARD'), ('POBOX', 'PO BOX'), ('MILITARY', 'MILITARY')], max_length=8)),
                ('is_decommissioned', models.BooleanField()),
                ('primary_city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RenameField(
            model_name='demographics',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='demographics',
            name='past_voting',
            field=models.CharField(choices=[('N', 'None'), ('F', 'Few'), ('H', 'About half'), ('M', 'Most'), ('A', 'All'), ('D', "I don't remember"), ('0', 'Not applicable')], default=None, max_length=1, verbose_name='Voting in Previous Elections'),
        ),
        migrations.CreateModel(
            name='OnboardCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboard_code', models.CharField(max_length=6)),
                ('is_registered', models.BooleanField(default=False)),
                ('registered_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
    ]
