# Generated by Django 3.1.7 on 2021-07-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210716_1646'),
        ('onboard', '0003_auto_20210716_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardcode',
            name='registered_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember'),
        ),
    ]
