# Generated by Django 3.1.7 on 2021-07-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0004_auto_20210716_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='pol_engagement',
            field=models.CharField(choices=[('N', 'Not at all engaged'), ('S', 'Slightly engaged'), ('M', 'Moderately engaged'), ('V', 'Very engaged'), ('E', 'Extremely engaged')], default=None, max_length=1, verbose_name='Political Engagement'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='race',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
