# Generated by Django 3.1.7 on 2021-07-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210724_2203'),
        ('onboard', '0005_auto_20210724_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardcode',
            name='is_registered',
        ),
        migrations.AlterField(
            model_name='onboardcode',
            name='registered_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.experimentmember'),
        ),
    ]
