# Generated by Django 4.2.2 on 2023-07-18 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_experimentsettings_exp_name'),
        ('onboard', '0008_alter_demographics_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProlificId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prolific_id', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
    ]
