# Generated by Django 4.2.2 on 2023-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0010_remove_demographics_pol_engagement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographics",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("W", "Female"),
                    ("N", "Non-binary"),
                    ("E", "Something else"),
                    ("P", "Prefer not to say"),
                ],
                default=None,
                max_length=1,
            ),
        ),
    ]
