# Generated by Django 4.2.2 on 2023-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0011_alter_demographics_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="demographics",
            name="pol_scale",
            field=models.CharField(
                choices=[
                    ("EL", "Extremely liberal"),
                    ("LI", "Liberal"),
                    ("SL", "Slightly liberal"),
                    ("MO", "Moderate; middle of the road"),
                    ("SC", "Slightly conservative"),
                    ("CO", "Conservative"),
                    ("EC", "Extremely conservative"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="Liberal Conservative",
            ),
        ),
    ]
