# Generated by Django 4.2.2 on 2023-10-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0012_demographics_pol_scale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demographics",
            name="pol_scale",
        ),
        migrations.AddField(
            model_name="demographics",
            name="pol_engagement",
            field=models.CharField(
                choices=[
                    ("N", "Not at all engaged"),
                    ("S", "Slightly engaged"),
                    ("M", "Moderately engaged"),
                    ("V", "Very engaged"),
                    ("E", "Extremely engaged"),
                ],
                default=None,
                max_length=1,
                null=True,
                verbose_name="Political Engagement",
            ),
        ),
        migrations.AddField(
            model_name="demographics",
            name="pol_party",
            field=models.CharField(
                choices=[
                    ("S", "Don't know / not sure"),
                    ("N", "Not registered with any political party"),
                    ("D", "Democratic Party"),
                    ("R", "Republican Party"),
                    ("I", "Independent"),
                    ("O", "Other"),
                ],
                default=None,
                max_length=1,
                null=True,
                verbose_name="Political Party",
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="age",
            field=models.CharField(
                choices=[
                    ("1", "18 to 24"),
                    ("2", "25 to 34"),
                    ("3", "35 to 44"),
                    ("4", "45 to 54"),
                    ("5", "55 to 64"),
                    ("6", "65 and above"),
                ],
                default=None,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="education",
            field=models.CharField(
                choices=[
                    ("<", "Less than high school"),
                    ("H", "High school graduate"),
                    ("C", "Some college"),
                    ("2", "2 year degree"),
                    ("4", "4 year degree"),
                    ("P", "Doctorate, masters, or other professional degrees"),
                ],
                default=None,
                max_length=1,
                verbose_name="Education Level",
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Man"),
                    ("W", "Woman"),
                    ("N", "Non-binary"),
                    ("E", "Something else"),
                    ("P", "Prefer not to say"),
                ],
                default=None,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="household_income",
            field=models.CharField(
                choices=[
                    ("<", "$15,000 or less"),
                    ("2", "$15,000 up to $25,999"),
                    ("3", "$26,000 up to $36,999"),
                    ("4", "$37,000 up to $49,999"),
                    ("5", "$50,000 up to $62,999"),
                    ("6", "$63,000 up to $78,999"),
                    ("7", "$79,000 up to $99,999"),
                    ("8", "$100,000 up to $129,999"),
                    ("9", "$130,000 up to $183,999"),
                    (">", "$184,000 or more"),
                ],
                default=None,
                max_length=1,
                verbose_name="Household Income",
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="pol_ideology",
            field=models.CharField(
                choices=[
                    ("VL", "Very liberal"),
                    ("LI", "Liberal"),
                    ("SL", "Slightly liberal"),
                    ("MO", "Moderate"),
                    ("SC", "Slightly conservative"),
                    ("CO", "Conservative"),
                    ("VC", "Very conservative"),
                    ("NA", "None of these describe my political leanings"),
                ],
                default=None,
                max_length=2,
                verbose_name="Political Ideology",
            ),
        ),
    ]
