# Generated by Django 4.2.2 on 2023-10-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0013_remove_demographics_pol_scale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demographics",
            name="pol_engagement",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="pol_party",
        ),
        migrations.AddField(
            model_name="demographics",
            name="pol_scale",
            field=models.CharField(
                choices=[
                    ("EL", "Extremely liberal"),
                    ("LI", "Liberal"),
                    ("SL", "Slightly liberal"),
                    ("MO", "Moderate; middle of the road"),
                    ("SC", "Slightly conservative"),
                    ("CO", "Conservative"),
                    ("EC", "Extremely conservative"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="Liberal Conservative",
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="age",
            field=models.CharField(
                choices=[
                    ("1", "18 to 24"),
                    ("2", "25 to 34"),
                    ("3", "35 to 50"),
                    ("4", "51 to 65"),
                    ("5", "65 and above"),
                ],
                default=None,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="education",
            field=models.CharField(
                choices=[
                    ("<", "Less than high school"),
                    ("H", "High school graduate"),
                    ("C", "Some college"),
                    ("4", "4 year college degree"),
                    (
                        "P",
                        "Advanced degree (doctorate, masters, or other professional degrees)",
                    ),
                ],
                default=None,
                max_length=1,
                verbose_name="Education Level",
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("W", "Female"),
                    ("N", "Non-binary"),
                    ("E", "Something else"),
                    ("P", "Prefer not to say"),
                ],
                default=None,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="household_income",
            field=models.CharField(
                choices=[
                    ("<", "$30,000 or less"),
                    ("2", "$30,000 up to $69,999"),
                    ("3", "$70,000 up to $99,999"),
                    ("4", "$100,000 up to $200,000"),
                    (">", "$200,000 or more"),
                ],
                default=None,
                max_length=1,
                verbose_name="Household Income",
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="pol_ideology",
            field=models.CharField(
                choices=[
                    ("SD", "Strong Democrat"),
                    ("WD", "Weak Democrat"),
                    ("LD", "Leaning Democrat"),
                    ("IN", "Independent"),
                    ("LR", "Leaning Republican"),
                    ("WR", "Weak Republican"),
                    ("SR", "Strong Republican"),
                ],
                default=None,
                max_length=2,
                verbose_name="Political Ideology",
            ),
        ),
    ]
