# Generated by Django 3.1.7 on 2021-04-02 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField()),
                ('recordId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url', models.TextField(max_length=2000)),
                ('transitionType', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('previousRecord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extension.urlrecord')),
            ],
        ),
    ]
