# Generated by Django 3.1.7 on 2021-04-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlrecord',
            old_name='endTime',
            new_name='EndTime',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='userId',
            new_name='ParticipantId',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='previousRecord',
            new_name='PreviousRecord',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='recordId',
            new_name='RecordId',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='startTime',
            new_name='StartTime',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='transitionType',
            new_name='TransitionType',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='url',
            new_name='Url',
        ),
    ]
