# Generated by Django 3.1.7 on 2021-05-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_auto_20210430_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlrecord',
            name='EndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
