# Generated by Django 3.1.7 on 2021-05-07 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_auto_20210507_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='day_iterations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.UUIDField()),
                ('currentDate', models.DateField(default=datetime.datetime(2021, 5, 7, 21, 6, 52, 933234))),
                ('number_of_site_visits', models.IntegerField(blank=True)),
            ],
        ),
    ]
