# Generated by Django 3.1.7 on 2021-05-07 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0004_day_iterations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_iterations',
            name='currentDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
