# Generated by Django 3.1.7 on 2021-07-16 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210716_1646'),
        ('extension', '0005_auto_20210507_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInterventionCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today, editable=False)),
                ('url', models.TextField(max_length=2000)),
                ('visit_count', models.IntegerField()),
                ('intervention_type', models.TextField(max_length=100)),
                ('participant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_alert_all', models.BooleanField(default=False)),
                ('participant_alert_intervention_type', models.TextField(max_length=100)),
                ('participant_message', models.TextField(max_length=17)),
                ('participant_alert_url', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TldRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld', models.TextField(max_length=256)),
                ('apply_intervention', models.BooleanField()),
                ('apply_collect_links', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VisibleLinkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_timestamp', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('linked_base_url', models.TextField(max_length=2000)),
                ('linked_full_url', models.TextField(max_length=2000)),
                ('referrer_url', models.TextField(max_length=2000)),
                ('tagname', models.TextField(max_length=6)),
                ('is_intersecting', models.BooleanField()),
                ('is_visible', models.BooleanField()),
                ('visibility_available', models.BooleanField()),
                ('participant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
                ('tld_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extension.tldrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='day_iterations',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='EndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='PreviousRecord',
            new_name='previous_record',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='RecordId',
            new_name='record_id',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='TransitionType',
            new_name='transition_type',
        ),
        migrations.RenameField(
            model_name='urlrecord',
            old_name='Url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='urlrecord',
            name='ParticipantId',
        ),
        migrations.RemoveField(
            model_name='urlrecord',
            name='StartTime',
        ),
        migrations.AddField(
            model_name='urlrecord',
            name='current_tab_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlrecord',
            name='participant_id',
            field=models.ForeignKey(default='e7f24579-f083-4eb2-8333-fcccd5df19a5', editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlrecord',
            name='previous_tab_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlrecord',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='urlrecord',
            name='tld',
            field=models.TextField(default='www.example.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyinterventioncount',
            name='tld_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extension.tldrecord'),
        ),
        migrations.AddField(
            model_name='urlrecord',
            name='tld_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extension.tldrecord'),
        ),
    ]
