# Generated by Django 3.1.7 on 2021-07-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0006_auto_20210716_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionalerts',
            name='participant_alert_active',
            field=models.BooleanField(default=False),
        ),
    ]
