# Generated by Django 3.1.7 on 2021-07-26 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0007_extensionalerts_participant_alert_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(default=datetime.datetime.now)),
                ('request_json', models.JSONField()),
                ('request_raw', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ExtensionAlerts',
            new_name='ExtensionAlert',
        ),
    ]
