# Generated by Django 3.1.7 on 2021-07-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0008_auto_20210726_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionerror',
            name='request_raw',
        ),
    ]
