# Generated by Django 3.1.7 on 2021-07-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0009_remove_extensionerror_request_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlrecord',
            name='previous_tab_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
