# Generated by Django 3.1.7 on 2021-07-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0010_auto_20210726_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionerror',
            name='message',
            field=models.CharField(default='NA', max_length=256),
        ),
    ]
