# Generated by Django 3.1.7 on 2021-07-27 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0011_extensionerror_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyinterventioncount',
            name='url',
        ),
        migrations.AddField(
            model_name='extensionalert',
            name='alert_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='extensionalert',
            name='participant_alert_intervention_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extensionalert',
            name='participant_alert_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='extensionalert',
            name='participant_message',
            field=models.CharField(max_length=17),
        ),
    ]
