# Generated by Django 3.1.7 on 2021-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0012_auto_20210727_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinterventioncount',
            name='intervention_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
