# Generated by Django 3.1.7 on 2021-07-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0013_auto_20210727_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiblelinkrecord',
            name='linked_base_url',
        ),
        migrations.RemoveField(
            model_name='visiblelinkrecord',
            name='linked_full_url',
        ),
        migrations.RemoveField(
            model_name='visiblelinkrecord',
            name='tld_record',
        ),
        migrations.AddField(
            model_name='visiblelinkrecord',
            name='linked_tld',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_link_link_tlds', to='extension.tldrecord'),
        ),
        migrations.AddField(
            model_name='visiblelinkrecord',
            name='linked_tld_url',
            field=models.CharField(default='example.com', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visiblelinkrecord',
            name='linked_url',
            field=models.CharField(default='example.com', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visiblelinkrecord',
            name='parent_page_url',
            field=models.CharField(default='example.com', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visiblelinkrecord',
            name='parent_tld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_link_parent_tlds', to='extension.tldrecord'),
        ),
        migrations.AlterField(
            model_name='visiblelinkrecord',
            name='referrer_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
