# Generated by Django 3.1.7 on 2021-07-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0014_auto_20210727_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiblelinkrecord',
            name='parent_page_url_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extension.urlrecord'),
        ),
    ]
