# Generated by Django 3.1.7 on 2021-07-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0015_visiblelinkrecord_parent_page_url_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiblelinkrecord',
            name='parent_page_url_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extension.urlrecord'),
        ),
    ]
