# Generated by Django 3.1.7 on 2021-07-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0016_auto_20210729_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlrecord',
            name='has_previous_record',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
