# Generated by Django 3.1.7 on 2021-07-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0017_urlrecord_has_previous_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyinterventioncount',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='urlrecord',
            options={'ordering': ['-start_time', '-end_time']},
        ),
        migrations.AlterModelOptions(
            name='visiblelinkrecord',
            options={'ordering': ['-visible_timestamp']},
        ),
    ]
