# Generated by Django 3.1.7 on 2023-04-12 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_experimentsettings_exp_name'),
        ('extension', '0018_auto_20210729_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('tweet_src', models.TextField(blank=True, null=True)),
                ('tweet_social_context', models.IntegerField(choices=[(0, 'None'), (1, 'Retweeted'), (2, 'Liked')], default=0)),
                ('tweet_feed_type', models.IntegerField(choices=[(0, 'None'), (1, 'For You'), (2, 'Following')], default=0)),
                ('tweet_body_text', models.TextField(blank=True, null=True)),
                ('retweet_was_clicked', models.BooleanField(default=False)),
                ('like_was_clicked', models.BooleanField(default=False)),
                ('reply_was_clicked', models.BooleanField(default=False)),
                ('participant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.experimentmember')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
