# Generated by Django 3.1.7 on 2023-04-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0019_tweetrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetrecord',
            name='parent_page_url_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extension.urlrecord'),
        ),
    ]
