# Generated by Django 3.1.7 on 2023-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0020_tweetrecord_parent_page_url_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetrecord',
            name='tweet_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweetrecord',
            name='tweet_visible_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweetrecord',
            name='tweet_feed_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'For You'), (2, 'Following')], default=0),
        ),
    ]
