# Generated by Django 4.2.2 on 2023-06-24 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0021_tweetrecord_promoted_visible_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetrecord',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
