# Generated by Django 4.2.2 on 2023-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0022_tweetrecord_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField()),
                ('tweet_record_id', models.UUIDField()),
                ('data_type', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
