# Generated by Django 4.2.2 on 2023-07-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0023_tweetmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField()),
                ('url_record_id', models.UUIDField()),
                ('data_type', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisibleLinkMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField()),
                ('visible_link_record_id', models.UUIDField()),
                ('data_type', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
