# Generated by Django 4.2.2 on 2023-07-20 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0024_urlmetadata_visiblelinkmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiblelinkrecord',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
