# Generated by Django 4.2.2 on 2023-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0025_visiblelinkrecord_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetrecord",
            name="user_handle",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
