# Generated by Django 4.2.2 on 2023-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0026_tweetrecord_user_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="visiblelinkmetadata",
            name="visible_link_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
