# Generated by Django 4.2.2 on 2023-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0027_visiblelinkmetadata_visible_link_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visiblelinkrecord",
            name="linked_tld_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
