# Generated by Django 4.2.2 on 2023-08-03 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0022_experimentmember_onboard_date"),
        ("extension", "0028_alter_visiblelinkrecord_linked_tld_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisibleLinkCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(default=datetime.date.today, editable=False),
                ),
                ("visible_link_count", models.IntegerField()),
                (
                    "participant_id",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.experimentmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
