# Generated by Django 4.2.2 on 2023-10-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0029_dailyvisiblelinkcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetrecord",
            name="tweet_verified",
            field=models.BooleanField(default=False),
        ),
    ]
